### ISSUE TITLE
Hatohol構築セクションについて

### ISSUE THREAD

**Issue by masa0612** [virtualtech/openstack-mitaka-docs#3]
はじめまして。Hatoholメインデベロッパーの中川です。
Hatohol構築セクションにおいていくつか気になる点があったので，箇条書きで申し訳ありませんがコメントいたします。
- Hatoholサーバーが動作するOSはCentOS7以降，またUbuntu14.04。 CentOS6向けのRPMパッケージは提供していますが，動作テストなどは行っていないため動作を保証できません。またUbuntu16.04についても同様に動作テストを行っていないので保証いたしかねます。
- 13-4-3, 13-4-4の説明が逆です。yumコマンドで各HAP2をインストールした後にhatohol-db-initiatorを実行しなければHatoholにHAP2を追加することはできません。
- 13-4-2セクションにおいてpythonモジュールのインストールを行っていますが，python-livestatusはNagios-Livestatusプラグインを用いる場合のみ必要なモジュールのため，この説明書では不要かと存じます。同様にlivestatusをインストールするためのpipも不要だと思います。また，python-pikaもHAP2のRPMパッケージの依存パッケージに指定しているため，インストール手順としては不要かと思われます。
- こちらの落ち度で申し訳ないのですが，16.04ではグラフ機能を用いた場合，Hatoholサーバーとの通信がpendingになってしまい，グラフの表示が正常にならない場合があります（恐らく経験があるかと思います。。。）。これはバグで，ネクストリリースで修正予定であるため，必要であればその旨記載したほうが良いかもしれません。

ざっくりで申し訳ありませんが，気になった点は以上になります。
なにか質問などあればお気軽にどうぞ！

**Comment by ytooyama** [comment]
ありがとうございます。対応します。

**Comment by ytooyama** [comment]
一部の設定はこちらのドキュメントを参照しています。
https://github.com/project-hatohol/hatohol/blob/master/doc/server/hap2/HowToUse.md
この手順冒頭でepel-erlang.repoの追加をしています。このリポジトリーはEL5向けのパッケージしか公開されておらず不要じゃないかと思うのですが、どうでしょうか。ちなみにEL7向けのerlangはEPELで配布しているようです。

**Comment by ytooyama** [comment]
1.0.0-b5で対応いたしました。未修正箇所は次のバージョンで対応します。
https://github.com/virtualtech/openstack-mitaka-docs/blob/1.0.0-b5/OpenStackMitaka.md

**Comment by masa0612** [comment]
> このリポジトリーはEL5向けのパッケージしか公開されておらず不要じゃないかと思うのですが、どうでしょうか。

おっしゃるとおりで，おそらくこのドキュメントを書いた人が勘違いしているのだと思います。
ご指摘ありがとうございます。

**Comment by masa0612** [comment]
修正内容確認しました。
GJです:+1:

**Comment by masa0612** [comment]
未修正箇所があるとのことなので，Issueクローズはお任せします。

**Comment by ytooyama** [comment]
以下、2項目を修正しました。
- https://github.com/virtualtech/openstack-mitaka-docs/commit/3838e899a4b43e45c6aa7f14ebc7a4406ba92c07
- https://github.com/virtualtech/openstack-mitaka-docs/commit/10ef935ad7f77d0d160f7452f570f6d734276f52

**Comment by ytooyama** [comment]
大丈夫そうなのでcloseします
